name: OSWAP ZAP Full Scan

on: [push]

jobs:      
   zap_scan:
      runs-on: ubuntu-latest
      name: Scan webapplication
      steps:
         - name: ZAP Scan
           uses: zaproxy/action-full-scan@v0.1.0
           with:
            target: 'https://www.dineezy.com/'
